@endpoint = http://localhost:3500/api

POST {{endpoint}}/movies
Content-Type: application/json

{
    "name": "Deadpool & Wolverine",
    "director": "Shawn Levy",
    "country": "usa",
    "rating": 7.8
}

###
GET {{endpoint}}/movies
Content-Type: application/json
Accept: application/json


###